name: "reverse_experiment"

data:
    src: "src"
    trg: "trg"
    # generate data with scripts/generate_reverse_task.py
    train: "test/data/mini_reverse/train"
    dev: "test/data/mini_reverse/dev"
    test: "test/data/mini_reverse/test"
    level: "word"
    lowercase: False
    max_sent_length: 12
    src_voc_min_freq: 0
    src_voc_limit: 100
    trg_voc_min_freq: 0
    trg_voc_limit: 100
    #src_vocab: "mini_reverse_model/src_vocab.txt"
    #trg_vocab: "mini_reverse_model/trg_vocab.txt"

testing:
    beam_size: 1
    alpha: 1.0

training:
    random_seed: 42
    optimizer: "adam"
    learning_rate: 0.001
    learning_rate_min: 0.0002
    weight_decay: 0.0
    clip_grad_norm: 1.0
    batch_size: 32
    batch_type: "sentence"
    scheduling: "plateau"
    patience: 5
    decrease_factor: 0.5
    early_stopping_metric: "eval_metric"
    epochs: 10
    validation_freq: 10
    logging_freq: 10
    eval_metric: "bleu"
    model_dir: "mini_reverse_model"
    overwrite: True
    shuffle: True
    use_cuda: False
    max_output_length: 12
    print_valid_sents: [0, 3, 6]
    keep_last_ckpts: 2

model:
    initializer: "xavier"
    embed_initializer: "normal"
    embed_init_weight: 0.1
    bias_initializer: "zeros"
    init_rnn_orthogonal: False
    lstm_forget_gate: 0.
    encoder:
        rnn_type: "lstm"
        embeddings:
            embedding_dim: 16
            scale: False
        hidden_size: 36
        bidirectional: True
        dropout: 0.1
        num_layers: 1
    decoder:
        rnn_type: "lstm"
        embeddings:
            embedding_dim: 16
            scale: False
        hidden_size: 36
        dropout: 0.1
        hidden_dropout: 0.1
        num_layers: 1
        input_feeding: True
        init_hidden: "bridge"
        attention: "luong"
dqn:
    epochs: 2000
    sample_size: 256
    lr: 0.00005
    egreed_max: 0.9
    egreed_min: 0.001
    gamma_max: 0.9
    gamma_min: 0.3
    nu_iter: 300
    mem_cap: 5000
    beam_min: 1
    beam_max: 50
    state_type: 'hidden'
    reward_type: 'bleu_batch'
    nu_pretrain: 0
    other_descrip: '_batch_test_'
